# Generated by Django 5.0.14 on 2026-03-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "landing_page",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("consent_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
