# Generated by Django 5.0.14 on 2026-07-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_id",
                    models.CharField(
                        db_index=True,
                        help_text="Short identifier used in redirect URL (e.g., /s/launch-batch-1)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable name for campaign", max_length=255
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="Destination URL where scanners are redirected",
                        max_length=2048,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "fg_color",
                    models.CharField(
                        default="#000000",
                        help_text="Foreground color in hex (e.g. #000000)",
                        max_length=7,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Background color in hex (e.g. #FFFFFF)",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("device_type", models.CharField(default="Unknown", max_length=50)),
                ("browser", models.CharField(default="Unknown", max_length=50)),
                ("os", models.CharField(default="Unknown", max_length=50)),
                ("referrer", models.URLField(blank=True, default="", max_length=2048)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="landing.qrcodecampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
