# Generated by Django 5.0.14 on 2026-07-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_qrcodecampaign_qrscanlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodecampaign",
            name="eye_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Corner square / eye color in hex or name (e.g. #E52225 or swole-red)",
                max_length=20,
            ),
        ),
    ]
